### ISSUE TITLE
komodo afertma

### ISSUE THREAD

**Issue by sonicdx10** [z-classic/z-nomp#104]
/home/dimi/z-nomp/node_modules/stratum-pool/lib/pool.js:576
                        result.response.miner = subsidy.miner;
                                                       ^

TypeError: Cannot read property 'miner' of undefined
    at /home/dimi/z-nomp/node_modules/stratum-pool/lib/pool.js:576:56
    at itemFinished (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by sonicdx10** [comment]
Fixed by KomodoTeam in last git update on their repo

**Comment by sennevb** [comment]
still got this error:

/root/pool/node_modules/typeforce/index.js:154
          throw tfSubError(e, i)
          ^
Error: Expected property "1" of type Satoshi, got Number NaN

**Comment by sonicdx10** [comment]
is Komodo what your trying to run? please check getblock temp about not to pay in rpc to founders ;)

**Comment by sonicdx10** [comment]
also check your past the 245k+ blocks

**Comment by sennevb** [comment]
is Komodo what your trying to run? please check getblock temp about not to pay in rpc to founders ;)

Show me your template then please..

**Comment by sennevb** [comment]
what do you mean with the blocks??

**Comment by sonicdx10** [comment]
komodo-cli getinfo  (check ## of blocks) should past ov 245k+ blocks, you need to sync to run without probs the pool  the issue is explained several times

**Comment by sonicdx10** [comment]
any pub server I can check?

**Comment by sennevb** [comment]
"blocks" : 247149,

its not a pub server :-(

**Comment by sonicdx10** [comment]
so, let's see, your komodo ports are diff than other coins? meaning RpcPorts-MiningPorts... if so, then, try to resync with everything inside the config folder deleted excluding the .cfg one file, if you have coins dump priv keys, and import em when the sync is almost/finished... also check blocktemplate the line 26 """     var blockReward = (this.rpcData.miner) * 100000000; """ as it is You Can Not run Zec on same stratum as Komodo because of the limitations, hope that help

**Comment by sennevb** [comment]
Ports are diff then other coins, have allready zcash ,zclassic and zdash running.
Itried resyncing allready..

but i dont hav  founders in my conf, cant find the adresses..

Also need to check blocktemplate

**Comment by sonicdx10** [comment]
as I said, you can NOT run Zec with Komodo at the same time because blocktemplate at line 26  as it's commented in #93   ;)

**Comment by sonicdx10** [comment]
check alvblock.com

**Comment by sennevb** [comment]
oh so that is the problem :-)

**Comment by sonicdx10** [comment]
yeye should find a fix soon

**Comment by sennevb** [comment]
avlblock.com is yours??

**Comment by sonicdx10** [comment]
yup alvblock, thank to z-nomp guys

**Comment by sennevb** [comment]
good luck mate!

**Comment by sonicdx10** [comment]
thx thx same to ya.... hve u tried mpos with z-nomp?

**Comment by sennevb** [comment]
no, plan was to stick to plain z-nomp

**Comment by sonicdx10** [comment]
GOOD GOOD that's GOOD

**Comment by sonicdx10** [comment]
@hellcatz how did you successfully run kmd while zec on same stratum?

**Comment by hellcatz** [comment]
With a little magic and lots of practice ;)
All "improvements" require changes to both node-stratum-pool and z-nomp projects to support all 3 coins at same time. Once I feel my mods are complete and have free time....I'll update my forks and do another pull request...it may be a few weeks.

**Comment by aayanl** [comment]
https://github.com/z-classic/node-stratum-pool/commit/6f709b5c5a6cf9c981609bf64ba018b98cfd7e18

**Comment by igorvoltaic** [comment]
Could anyone help me? What am i doing wrong?
Or do i need to fix something to be able to start komodo pool?
dumpprivkey gives me the key and daemon is running. 

```shell
2018-05-03 16:06:29 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-05-03 16:06:29 [Master]	[CLI] CLI listening on port 17117
2018-05-03 16:06:29 [PPLNT]	[komodo] TimeShare processing setup with redis (127.0.0.1:6379)
2018-05-03 16:06:29 [Payments]	[komodo]  minimum paymentInterval of 120 seconds recommended.
2018-05-03 16:06:29 [Payments]	[komodo] komodo requireShielding: false
2018-05-03 16:06:29 [Payments]	[komodo] komodo minConf: 10
2018-05-03 16:06:29 [Payments]	[komodo] komodo payments txfee reserve: 0.0004
2018-05-03 16:06:29 [Payments]	[komodo] komodo maxBlocksPerPayment: 3
2018-05-03 16:06:29 [Payments]	[komodo] komodo PPLNT: false, time period: 0.51
2018-05-03 16:06:29 [Payments]	[komodo] Daemon does not own pool address - payment processing can not be done with this daemon, {"isvalid":false}
2018-05-03 16:06:29 [Payments]	[komodo] Daemon does not own pool address - payment processing can not be done with this daemon, {"isvalid":false}
2018-05-03 16:06:29 [Website]	[Server] Website started on 127.0.0.1:8080
2018-05-03 16:06:29 [Website]	[komodo] Could not dumpprivkey for komodo {"code":-5,"message":"Invalid Komodo address"}
2018-05-03 16:06:29 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2018-05-03 16:06:29 [Pool]	[komodo] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2018-05-03 16:06:29 [Pool]	[komodo] (Thread 1) Could not start pool, error with init batch RPC call: {"type":"request error","message":"read ECONNRESET"}
2018-05-03 16:06:30 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
2018-05-03 16:06:30 [Pool]	[komodo] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2018-05-03 16:06:30 [Pool]	[komodo] (Thread 2) Could not start pool, error with init batch RPC call: {"type":"request error","message":"read ECONNRESET"}
2018-05-03 16:06:30 [Master]	[PoolSpawner] Spawned 1 pool(s) on 4 thread(s)
2018-05-03 16:06:30 [Switching]	[Setup] (Thread 3) Loading last proxy state from redis
2018-05-03 16:06:30 [Pool]	[komodo] (Thread 3) Share processing setup with redis (127.0.0.1:6379)
2018-05-03 16:06:30 [Pool]	[komodo] (Thread 3) Could not start pool, error with init batch RPC call: {"type":"request error","message":"read ECONNRESET"}
2018-05-03 16:06:30 [Switching]	[Setup] (Thread 4) Loading last proxy state from redis
2018-05-03 16:06:30 [Pool]	[komodo] (Thread 4) Share processing setup with redis (127.0.0.1:6379)
2018-05-03 16:06:30 [Pool]	[komodo] (Thread 4) Could not start pool, error with init batch RPC call: {"type":"request error","message":"read ECONNRESET"}
```

**Comment by sennevb** [comment]
Is the deamon on same server?
Try rpcallowip=127.0.0.1 in your coins .conf  if it's on the same..

**Comment by igorvoltaic** [comment]
yep, same server and interestingly zen pool is just runs without any problems

**Comment by igorvoltaic** [comment]
several days i was editing comments in komodo.json :) well, thanks for the attention & time anyways :)
