### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by Woor** [z-classic/z-nomp#108]
I followed https://zdeveloper.org/wiki:z-nomp_install to the letter.

Tried multiple times, each time with a clean OS install, yet every time the result is:

2017-03-29 16:52:39 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-03-29 16:52:39 [Master]	[CLI] CLI listening on port 17117
2017-03-29 16:52:40 [Master]	[PoolSpawner] Spawned 1 pool(s) on 2 thread(s)
2017-03-29 16:52:40 [Website]	[Server] Website started on 0.0.0.0:8080
(node:13515) DeprecationWarning: (node-watch) First param in callback function  is replaced with event name since 0.5.0, use  `(evt, filename) => {}` if you want to get the filename
2017-03-29 16:52:40 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2017-03-29 16:52:40 [Pool]	[zcash] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
/home/coke/z-nomp/node_modules/bs58check/index.js:48
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/home/coke/z-nomp/node_modules/bs58check/index.js:48:23)
    at Object.fromBase58Check (/home/coke/z-nomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/home/coke/z-nomp/node_modules/stratum-pool/lib/transactions.js:87:46)
    at new BlockTemplate (/home/coke/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/home/coke/z-nomp/node_modules/stratum-pool/lib/jobManager.js:123:32)
    at /home/coke/z-nomp/node_modules/stratum-pool/lib/pool.js:578:66
    at itemFinished (/home/coke/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/coke/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/coke/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/coke/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
2017-03-29 16:52:40 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...

Spamming that last part over and over and not being connectable by workers obviously.

**Comment by Woor** [comment]
Also worth noting that the same running zcash daemon works fine with your equihash-solomining.
Double checked all addresses, ports etc. No clue what's wrong with z-nomp.

**Comment by sonicdx10** [comment]
I'm getting that message while wakingup ZeroPool but it runs well after it

**Comment by aayanl** [comment]
What node version and daemon version are you using?

**Comment by Woor** [comment]
coke@deb64:~/zcash$ ./src/zcash-cli --version
Zcash RPC client version v1.0.8

coke@deb64:~/zcash$ node -v
v7.8.0
coke@deb64:~/zcash$ npm -v
4.2.0

**Comment by aayanl** [comment]
are you using a t1 or t3 address? I can't seem to reproduce this issue unless if I put in an invalid address

**Comment by Woor** [comment]
I use freshly generated t1 addresses.

This is the relevant part of my pool_configs/zcash.json file:

    "enabled": true,
    "coin": "zcash.json",

    "address": "t1bmjnk9mWmeMZaeqmR6gA74hStC1LRnhgt",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zcBF4LwNpxC5AAiNtKMJAr727P1boZTQk6sg3n7W2NerCWSKnSqUDXpA8KRZcDEF2czUYs8bRxFHF6H2P9ueeSGP8FrqY2J",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1JxqDC5G18bkihQBQCUb9pVuVoPGGjnSSo",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

On my other tries I also used freshly generated addresses.

I will re-install OS, zcash daemon as well as z-nomp yet again tomorrow morning and post my config.json and zcash.json files. (minus the passwords ofc ;))

I feel like I'm being super dumb somehow, it must be something really obvious that totally escapes me...

**Comment by hellcatz** [comment]
I believe I had a similar error in the past when the founders rewards were not quite right before node-stratum was fixed.
If it is simple problem...maybe...it could be that your running an outdated node-stratum inside z-nomp?

The invalid checksum error is being thrown from node-stratum this line of code.
First: https://github.com/hellcatz/node-stratum-pool/blob/patch-1/lib/blockTemplate.js#L49
Then: https://github.com/hellcatz/node-stratum-pool/blob/patch-1/lib/transactions.js#L35
OR: https://github.com/hellcatz/node-stratum-pool/blob/patch-1/lib/transactions.js#L73

It appears to have an issue parsing your pool address. `t1bmjnk9mWmeMZaeqmR6gA74hStC1LRnhgt`
OR It is having an issue parsing the founders reward address.

I have changed blockTemplate.js in attempt to help; just in case it's getting payFoundersReward and founders object mixed up. It may or may not fix your issue.
https://github.com/hellcatz/node-stratum-pool/tree/patch-1

Compare: https://github.com/z-classic/node-stratum-pool/compare/master...hellcatz:patch-1

**Comment by Woor** [comment]
I knew I was being an idiot!

@hellcatz You are king. The zcash_example.json contains:

    "rewardRecipients": {
        "": 0.2,
        "": 0.3
    },

And I missed that.

"rewardRecipients": {
    },

does fix the issue, as does entering the correct address which I should have done. I almost gave up there, turns out the problem is me being blind/stupid.

**Comment by Woor** [comment]
Thanks for your time and patience, I really appreciate it.

**Comment by tecnoinfoch** [comment]
please, help me:

npm start

> z-nomp@0.0.4 start /home/pool/zcash/znomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2017-08-04 12:53:35 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-08-04 12:53:35 [Master]    [CLI] CLI listening on port 17117
2017-08-04 12:53:35 [PPLNT]     [zcash] TimeShare processing setup with redis (127.0.0.1:6379)
2017-08-04 12:53:36 [Website]   [Server] Website started on 0.0.0.0:8080
2017-08-04 12:53:36 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2017-08-04 12:53:36 [Pool]      [zcash] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
/home/pool/zcash/znomp/node_modules/base-x/index.js:52
    if (string.length === 0) return Buffer.allocUnsafe(0)
              ^

TypeError: Cannot read property 'length' of undefined
    at decodeUnsafe (/home/pool/zcash/znomp/node_modules/base-x/index.js:52:15)
    at Object.decode (/home/pool/zcash/znomp/node_modules/base-x/index.js:81:15)
    at Object.decode (/home/pool/zcash/znomp/node_modules/bs58check/index.js:44:23)
    at Object.fromBase58Check (/home/pool/zcash/znomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/transactions.js:97:52)
    at new BlockTemplate (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /home/pool/zcash/znomp/node_modules/stratum-pool/lib/pool.js:588:66
    at itemFinished (/home/pool/zcash/znomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/pool/zcash/znomp/node_modules/stratum-pool/lib/daemon.js:169:17
2017-08-04 12:53:36 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
2017-08-04 12:53:36 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2017-08-04 12:53:36 [Pool]      [zcash] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2017-08-04 12:53:36 [Master]    [PoolSpawner] Spawned 1 pool(s) on 4 thread(s)
/home/pool/zcash/znomp/node_modules/base-x/index.js:52
    if (string.length === 0) return Buffer.allocUnsafe(0)
              ^

TypeError: Cannot read property 'length' of undefined

**Comment by Andrewblood** [comment]
2017-08-04 12:53:36 [Website] [Server] Website started on 0.0.0.0:8080
Website IP not changed in

**Comment by sennevb** [comment]
there are problems when you use nodeV6, upgarde to nodejs V8 , remove node_modules and do npm update and npm install again

**Comment by sennevb** [comment]
@Andrewblood 0.0.0.0 binds to all network interfaces, so if you have multiple ip's it will bind to all
