### ISSUE TITLE
Acknowledge TLS ports has TLS on the front-end 

### ISSUE THREAD

**Issue by aayanl** [z-classic/z-nomp#125]

**Comment by ghostnegotiator** [comment]
I'll have a look at in in a seccond...

**Comment by ghostnegotiator** [comment]
Error produced:

Upgrade/Upgrade steps:
```
rm -r node_modules
git pull
git checkout master
npm install
```

```
TypeError: Cannot read property 'key' of undefined
    at new module.exports (/home/redacted/z-nomp/libs/website.js:336:67)
    at Object.<anonymous> (/home/redacted/z-nomp/init.js:80:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
```

**Comment by ghostnegotiator** [comment]
After some tweaking its confirmed working & in production at https://zpool.it

Apache2 config will be posted in a bit.

**Comment by aayanl** [comment]
What I meant is that the frontend doesnt say if ports have TLS or not

**Comment by ghostnegotiator** [comment]
Frontend still loads insecure resources.
