### ISSUE TITLE
Error: equi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ykla** [z-classic/z-nomp#134]
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp# node init
/root/z-nomp/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: equi.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/root/z-nomp/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/root/z-nomp/node_modules/equihashverify/index.js:1:99)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp#

**Comment by ykla** [comment]
I have set $PATH and environment.

**Comment by ghostnegotiator** [comment]
Heya,

It seems you're missing dependcies.

Use npm update first:
rm -rf node_modules
npm update
npm install

**Comment by ykla** [comment]
I tried, but the result is still the case.

**Comment by hellcatz** [comment]
`npm start`  not init?

**Comment by ykla** [comment]
npm start is normal

**Comment by aayanl** [comment]
You need to use npm start because of the equihashverify module https://github.com/z-classic/z-nomp/blob/master/package.json#L58

**Comment by ykla** [comment]
ok
