### ISSUE TITLE
Error: Fork 0 died, spawning replacement worker..

### ISSUE THREAD

**Issue by gugukSI** [z-classic/z-nomp#171]
/z-nomp/node_modules/stratum-pool/lib/merkleTree.js:9
    return Object.values(result)[2].root;
                  ^

TypeError: Object.values is not a function
    at calcRoot (/z-nomp/node_modules/stratum-pool/lib/merkleTree.js:9:19)
    at Object.exports.getRoot (/z-nomp/node_modules/stratum-pool/lib/merkleTree.js:20:18)
    at new BlockTemplate (/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:54:30)
    at JobManager.processTemplate (/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at z-nomp/node_modules/stratum-pool/lib/pool.js:588:66
    at itemFinished (/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)

**Comment by aayanl** [comment]
can you give more info like your pool config?

**Comment by sennevb** [comment]
no info received, closing this
