### ISSUE TITLE
Forever command

### ISSUE THREAD

**Issue by gwbraa** [z-classic/z-nomp#200]
Hey guys

When running

sudo forever start init.js

I am getting this error
`/home/user/z-nomp/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: equi.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:602:18)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at bindings (/home/user/z-nomp/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/user/z-nomp/node_modules/equihashverify/index.js:1:99)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
error: Forever detected script exited with code: 1
`
But when I am running npm start runs 100%

Do you guys know why? sorry for the noob question

**Comment by TheComputerGenie** [comment]
`forever start -c "npm start" /path/to/app/dir/`
https://github.com/foreverjs/forever/issues/540#issuecomment-37762716

**Comment by thghdbs** [comment]
Try:
sudo forever --minUptime 1000 --spinSleepTime 1000 --sourceDir ~/z-nomp start -c "npm start" ./
