### ISSUE TITLE
npm start "Error: invalid checksum"

### ISSUE THREAD

**Issue by dopro17** [z-classic/z-nomp#229]
When starts this error came

Error: Invalid checksum
    at Object.decode (/home/zcash/z-nomp/node_modules/bs58check/index.js:46:23)
    at Object.fromBase58Check (/home/zcash/z-nomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/home/zcash/z-nomp/node_modules/stratum-pool/lib/transactions.js:127:42)
    at new BlockTemplate (/home/zcash/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/home/zcash/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /home/zcash/z-nomp/node_modules/stratum-pool/lib/pool.js:588:66
    at itemFinished (/home/zcash/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/zcash/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/zcash/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/zcash/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
2017-11-08 02:11:28 [Master]	[PoolSpawner] Fork 1 died, spawning replacement worker...
/home/zcash/z-nomp/node_modules/bs58check/index.js:46
  if (!payload) throw new Error('Invalid checksum')
                ^

System setup
Ubuntu 16.04.1 LTS
npm 5.5.1
nodejs 9.0.0 (/usr/local/bin/node)
(but on ubuntu original is 4.2.6)

**Comment by dopro17** [comment]
Get the solution in other issue.
