### ISSUE TITLE
Error: Expected property "1" of type Satoshi, got Number 125000000000269150

### ISSUE THREAD

**Issue by remrat** [z-classic/z-nomp#234]
Running Bitcoin Gold wallet, with complete blockchain.

When I start up z-nomp, the following error is displayed.  This error only started showing after 100% of the blockchain was downloaded.  

> z-nomp@0.0.4 start /root/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2017-11-15 14:56:11 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-11-15 14:56:11 [Master]    [CLI] CLI listening on port 17117
2017-11-15 14:56:11 [PPLNT]     [bitcoin gold] TimeShare processing setup with redis (127.0.0.1:6379)
2017-11-15 14:56:11 [Master]    [PoolSpawner] Spawned 1 pool(s) on 2 thread(s)
2017-11-15 14:56:12 [Website]   [Server] Website started on 0.0.0.0:80
2017-11-15 14:56:12 [Payments]  [bitcoin gold]  minimum paymentInterval of 120 seconds recommended.
2017-11-15 14:56:12 [Payments]  [bitcoin gold] bitcoin gold requireShielding: true
2017-11-15 14:56:12 [Payments]  [bitcoin gold] bitcoin gold minConf: 10
2017-11-15 14:56:12 [Payments]  [bitcoin gold] bitcoin gold payments txfee reserve: 0.0004
2017-11-15 14:56:12 [Payments]  [bitcoin gold] bitcoin gold maxBlocksPerPayment: 3
2017-11-15 14:56:12 [Payments]  [bitcoin gold] bitcoin gold PPLNT: false, time period: 0.51
2017-11-15 14:56:12 [Payments]  [bitcoin gold] Error with payment processing daemon {"code":-32601,"message":"Method not found"}
2017-11-15 14:56:12 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2017-11-15 14:56:12 [Pool]      [bitcoin gold] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2017-11-15 14:56:12 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2017-11-15 14:56:12 [Pool]      [bitcoin gold] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2017-11-15 14:56:12 [Pool]      [bitcoin gold] (Thread 1) No rewardRecipients have been setup which means no fees will be taken
2017-11-15 14:56:12 [Pool]      [bitcoin gold] (Thread 2) No rewardRecipients have been setup which means no fees will be taken

/root/z-nomp/node_modules/typeforce/index.js:159
          throw tfSubError(e, i)
          ^
Error: Expected property "1" of type Satoshi, got Number 125000000000248140
    at tfSubError (/root/z-nomp/node_modules/typeforce/errors.js:93:9)
    at /root/z-nomp/node_modules/typeforce/index.js:159:17
    at Array.every (<anonymous>)
    at _tuple (/root/z-nomp/node_modules/typeforce/index.js:155:20)
    at typeforce (/root/z-nomp/node_modules/typeforce/index.js:196:9)
    at Transaction.addOutput (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/transaction.js:268:3)
    at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:118:12)
    at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:588:66

/root/z-nomp/node_modules/typeforce/index.js:159
          throw tfSubError(e, i)
          ^
Error: Expected property "1" of type Satoshi, got Number 125000000000248140
    at tfSubError (/root/z-nomp/node_modules/typeforce/errors.js:93:9)
    at /root/z-nomp/node_modules/typeforce/index.js:159:17
    at Array.every (<anonymous>)
    at _tuple (/root/z-nomp/node_modules/typeforce/index.js:155:20)
    at typeforce (/root/z-nomp/node_modules/typeforce/index.js:196:9)
    at Transaction.addOutput (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/transaction.js:268:3)
    at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:118:12)
    at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:588:66
2017-11-15 14:56:12 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...

**Comment by TheComputerGenie** [comment]
bgold will not work with z-nomp because the block headers are different from a "standard" zcash fork and the edits need to be made to the stratum layer (not the z-nomp layer).

**Comment by remrat** [comment]
Do you know which file needs to be edited?

**Comment by TheComputerGenie** [comment]
https://github.com/z-classic/node-stratum-pool/blob/master/lib/blockTemplate.js#L74

**Comment by remrat** [comment]
Thank you for the file and location..  Unfortunately, that is over my head...

Here is the info I have:
Because of the PoW change, all the Bitcoin pools are incompatible with Bitcoin Gold. Zcash pools can                 be​ ​used​ ​with​ ​some​ ​tweaks. 
● The​ ​block​ ​header​ ​format​ ​is​ ​mostly​ ​compatible​ ​with​ ​Zcash​ ​except: ○ `nVersion`​ ​is​ ​not​ ​4.​ ​Instead​ ​it’s​ ​defined​ ​by​ ​BIP9. ○ The​ ​first​ ​4​ ​bytes​ ​of​ ​`hashReserved`​ ​(32​ ​lows​ ​bits)​ ​are​ ​used​ ​to​ ​store​ ​the​ ​block​ ​height. ● Other​ ​than​ ​the​ ​block​ ​height,​ ​the​ ​block​ ​format​ ​is​ ​the​ ​same​ ​as​ ​Bitcoin. ● No​ ​per-block​ ​founder​ ​rewards. ● Block​ ​subsidy​ ​and​ ​block​ ​interval​ ​is​ ​the​ ​same​ ​as​ ​Bitcoin​ ​rather​ ​than​ ​Zcash.

**Comment by TheComputerGenie** [comment]
If it's over your head, then there's no point in trying to walk you through it - use the z-nomp fork that the bgold "dev" put out

**Comment by remrat** [comment]
I agree.  thank you for your help...
