### ISSUE TITLE
Weird errors on the pool.

### ISSUE THREAD

**Issue by onnz423** [z-classic/z-nomp#235]
I have tried multiple ports for the website, but still it gives the EADDRNOTAVAIL error. Have tried running npm start as sudo too. Also by googling "Error: Expected property "1" of type Satoshi, got Number" i cannot find enough information to know where the problem actually originates from. Anyone could help me with this problem?

> z-nomp@0.0.4 start /home/user/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2017-11-17 08:46:24 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-11-17 08:46:24 [Master]	[CLI] CLI listening on port 5050
2017-11-17 08:46:24 [PPLNT]	[bitcoin gold] TimeShare processing setup with redis (127.0.0.1:6379)
2017-11-17 08:46:24 [Payments]	[bitcoin gold]  minimum paymentInterval of 120 seconds recommended.
2017-11-17 08:46:24 [Payments]	[bitcoin gold] bitcoin gold requireShielding: false
2017-11-17 08:46:24 [Payments]	[bitcoin gold] bitcoin gold minConf: 10
2017-11-17 08:46:24 [Payments]	[bitcoin gold] bitcoin gold payments txfee reserve: 0.000005
2017-11-17 08:46:24 [Payments]	[bitcoin gold] bitcoin gold maxBlocksPerPayment: 3
2017-11-17 08:46:24 [Payments]	[bitcoin gold] bitcoin gold PPLNT: false, time period: 0.51
2017-11-17 08:46:24 [Payments]	[bitcoin gold] Payment processing setup with daemon (pool@127.0.0.1:8332) and redis (127.0.0.1:6379)
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRNOTAVAIL myip:21519
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at listenOnMasterHandle (net.js:1427:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at process.emit (events.js:164:20)
    at emit (internal/child_process.js:790:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2017-11-17 08:46:24 [Master]	[Website] Website process died, spawning replacement...
2017-11-17 08:46:24 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2017-11-17 08:46:24 [Pool]	[bitcoin gold] (Thread 1) Share processing setup with redis (127.0.0.1:6379)

/home/ubuntu/z-nomp/node_modules/typeforce/index.js:159
          throw tfSubError(e, i)
          ^
Error: Expected property "1" of type Satoshi, got Number 125000000000007630
    at tfSubError (/home/ubuntu/z-nomp/node_modules/typeforce/errors.js:93:9)
    at /home/ubuntu/z-nomp/node_modules/typeforce/index.js:159:17
    at Array.every (<anonymous>)
    at _tuple (/home/ubuntu/z-nomp/node_modules/typeforce/index.js:155:20)
    at typeforce (/home/ubuntu/z-nomp/node_modules/typeforce/index.js:196:9)
    at Transaction.addOutput (/home/ubuntu/z-nomp/node_modules/stratum-pool/node_modules/bitcoinjs-lib-zcash/src/transaction.js:268:3)
    at Object.exports.createGeneration (/home/ubuntu/z-nomp/node_modules/stratum-pool/lib/transactions.js:118:12)
    at new BlockTemplate (/home/ubuntu/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/home/ubuntu/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /home/ubuntu/z-nomp/node_modules/stratum-pool/lib/pool.js:588:66
2017-11-17 08:46:24 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...
2017-11-17 08:46:25 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
2017-11-17 08:46:25 [Pool]	[bitcoin gold] (Thread 2) Share processing setup with redis (127.0.0.1:6379)

**Comment by TheComputerGenie** [comment]
https://github.com/z-classic/z-nomp/issues/234
https://github.com/z-classic/z-nomp/issues/230

**Comment by onnz423** [comment]
@TheComputerGenie thanks alot! Closing this issue.
