### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by Coronon** [z-classic/z-nomp#237]
If i start the pool, everything seems to be working fine until this happens:

```
/home/btcgpu/z-nomp-bitcoin-gold/node_modules/bs58check/base.js:40
    if (!payload) throw new Error('Invalid checksum')
                  ^

Error: Invalid checksum
    at Object.decode (/home/btcgpu/z-nomp-bitcoin-gold/node_modules/bs58check/base.js:40:25)
    at Object.fromBase58Check (/home/btcgpu/z-nomp-bitcoin-gold/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/home/btcgpu/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/transactions.js:75:42)
    at new BlockTemplate (/home/btcgpu/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/blockTemplate.js:36:35)
    at JobManager.processTemplate (/home/btcgpu/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/jobManager.js:141:32)
    at /home/btcgpu/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/pool.js:581:66
    at itemFinished (/home/btcgpu/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /home/btcgpu/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/btcgpu/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/btcgpu/z-nomp-bitcoin-gold/node_modules/stratum-pool/lib/daemon.js:95:17)
2017-11-19 19:06:14 [Master]	[PoolSpawner] Fork 1 died, spawning replacement worker...
```

Please help me

**Comment by TheComputerGenie** [comment]
See:
https://github.com/z-classic/z-nomp/issues/234
https://github.com/z-classic/z-nomp/issues/230
