### ISSUE TITLE
Zen Cash Payment processing

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [z-classic/z-nomp#246]
Hi when I payment processing on for zen cash I get this error. Any help would be greatful. I noticed this was mentioned on another issue but it did not have a solution attached to it.

/home/jamie/z-nomp/libs/paymentProcessor.js:738
                        round.confirmations = parseInt((tx.result.confirmations || 0));
                                                                 ^

TypeError: Cannot read property 'confirmations' of null
    at /home/jamie/z-nomp/libs/paymentProcessor.js:738:66
    at Array.forEach (<anonymous>)
    at /home/jamie/z-nomp/libs/paymentProcessor.js:729:31
    at /home/jamie/z-nomp/node_modules/stratum-pool/lib/daemon.js:133:13
    at parseJson (/home/jamie/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/jamie/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by michaelotis** [comment]
I too am having this issue. Blocks sit pending forever.

**Comment by michaelotis** [comment]
@jamiejacksoncumbria I figured it out.

There must be something screwy with a script or redis. This is how I fixed it.

- Install redis-commander (https://github.com/joeferner/redis-commander)
- Start redis-commander

**- To start, if you have a set called "blocksConfirmed" already then I don't know if my solution is for you**

- Under zen, you'll see a set called "blocksPending"
- Find your very first block you ever did mine, you'll have to reference the block height, hash or tx id and match it up with the member. Double click on it, copy the information inside the text box. Then click Remove Member. Make sure you have the information copied!

- If the blocksConfirmed set is NOT created, right click on zen and click "Add Key"
- Add blocksConfirmed after "zen:" in the key input box
- Set to type "Set"
- Copy the information we just copied into the Value box, click Save.

Give it about 10-15 seconds and you should see the block says *PAID* on the stats page and all other blocks have confirmation numbers instead of *PENDING*

All miners also now have immature balances.
