### ISSUE TITLE
Error when i run npm update

### ISSUE THREAD

**Issue by peterkristel** [z-classic/z-nomp#255]
root@server1:~/z-nomp# npm update

> equihashverify@0.0.1 install /root/z-nomp/node_modules/equihashverify
> node-gyp rebuild

make: Entering directory '/root/z-nomp/node_modules/equihashverify/build'
  CC(target) Release/obj.target/libequi/src/equi/equi.o
../src/equi/equi.c:18:10: fatal error: sodium.h: No such file or directory
 #include <sodium.h>
          ^~~~~~~~~~
compilation terminated.
libequi.target.mk:102: recipe for target 'Release/obj.target/libequi/src/equi/equi.o' failed
make: *** [Release/obj.target/libequi/src/equi/equi.o] Error 1
make: Leaving directory '/root/z-nomp/node_modules/equihashverify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/z-nomp/node_modules/equihashverify
gyp ERR! node -v v9.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! equihashverify@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the equihashverify@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-21T13_08_51_283Z-debug.log

**Comment by kalmare** [comment]
i think you need to install libsodium-dev

**Comment by trofa13** [comment]
I've had the same issue, re-installing libsodium-dev helped. Thaks @kalmare !
