### ISSUE TITLE
installing issue - Error: Cannot find module 'bignum'

### ISSUE THREAD

**Issue by helxsz** [z-classic/z-nomp#261]
when installing , such issue is happening

```
> z-nomp@0.0.4 start /root/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

module.js:544
    throw err;
    ^

Error: Cannot find module 'bignum'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/z-nomp/node_modules/base58-native/base58.js:2:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! z-nomp@0.0.4 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the z-nomp@0.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-03T08_58_03_864Z-debug.log
```

I tried such commands
```
cd node_modules
git clone git://github.com/justmoon/node-bignum.git
cd node-bignum
npm install
```

but when calling npm start, the issue is still not resolved

**Comment by helxsz** [comment]
npm install bignum
