### ISSUE TITLE
TypeError: Expected String

### ISSUE THREAD

**Issue by bigenergy** [z-classic/z-nomp#275]
```
2018-01-22 15:20:19 [Master]    [PoolSpawner] Fork 11 died, spawning replacement worker...
/root/z-nomp/node_modules/base-x/index.js:52
    if (typeof string !== 'string') throw new TypeError('Expected String')
                                    ^

TypeError: Expected String
    at decodeUnsafe (/root/z-nomp/node_modules/base-x/index.js:52:43)
    at Object.decode (/root/z-nomp/node_modules/base-x/index.js:81:18)
    at Object.decode (/root/z-nomp/node_modules/bs58check/base.js:39:25)
    at Object.fromBase58Check (/root/z-nomp/node_modules/stratum-pool/node_modules/bitcoinjs-lib-zcash/src/address.js:11:27)
    at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:97:52)
    at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/root/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:588:66
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
2018-01-22 15:20:19 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...
```

**Comment by bigenergy** [comment]
help me pls!

**Comment by AlexSpain** [comment]
Look coin demon logs

**Comment by red0bear** [comment]
@AlexSpain  where exact to look ? im facing the same problem.

**Comment by red0bear** [comment]
i go in index.js and put in begin console.log(string); to what happen in function function decodeUnsafe (string)  ......... so it reads the first  one address but second is undefined. 

here it reads the address from zcash example to configure zcash ?
