### ISSUE TITLE
z-nomp    Error: Cannot find module 'bitcoinjs-lib-zcash'. 

### ISSUE THREAD

**Issue by llbrunoll** [z-classic/z-nomp#279]
before this errors, I had error related to stratum-pool 

Error  "can't find ... stratum_pool"

which went through after I did:
sudo apt install libsodium-dev

and  then
Error: Cannot find module '/home/z-nomp/node_modules/bignum/binding/bignum.node'

which went through after I did:
npm install node-pre-gyp

but now I see this next error. And found no fix. Any idea?

/home/z-nomp# npm start

> z-nomp@0.0.4 start /home/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

module.js:557
    throw err;
    ^

Error: Cannot find module 'bitcoinjs-lib-zcash'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/z-nomp/node_modules/stratum-pool/lib/transactions.js:1:77)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! z-nomp@0.0.4 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the z-nomp@0.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-26T20_40_57_250Z-debug.log

**Comment by llbrunoll** [comment]
Just solve it by following this: 

Upgrading Z-NOMP

When updating Z-NOMP to the latest code its important to not only git pull the latest from this repo, but to also update the node-stratum-pool and node-multi-hashing modules, and any config files that may have been changed.

Inside your Z-NOMP directory (where the init.js script is:
"z-nomp/node_modules/equihashverify/build/Release/") do "git pull" to get the latest Z-NOMP code.

Remove the dependenices by deleting the node_modules directory with "rm -r node_modules"

Run "npm update" to force updating/reinstalling of the dependencies.

then just start again: "nom start" 

that solved the issue, and actually avoided also the other two Errors

Error "can't find ... stratum_pool"
Error: Cannot find module '/home/z-nomp/node_modules/bignum/binding/bignum.node'

So, it might be a fix for them as well.
