### ISSUE TITLE
TypeError: Cannot read property 'getStratumServer' of undefined

### ISSUE THREAD

**Issue by ankitkaran99** [z-classic/z-nomp#289]
**I am getting follwing error when connecting nheqminer to my pool -**

/home/ubuntu/z-nomp-bitcoin-gold/libs/poolWorker.js:274
                            pools[initalPool].getStratumServer().handleNewClient(socket);
                                              ^

TypeError: Cannot read property 'getStratumServer' of undefined
    at Server.<anonymous> (/home/ubuntu/z-nomp-bitcoin-gold/libs/poolWorker.js:274:47)
    at Server.emit (events.js:160:13)
    at Object.onconnection (net.js:1582:8)
    at onconnection (internal/cluster/child.js:168:12)
    at Worker.onmessage (internal/cluster/child.js:43:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at process.emit (events.js:165:20)
    at emit (internal/child_process.js:790:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2018-02-13 05:27:03 [Master]    [PoolSpawner] Fork 5 died, spawning replacement worker...

**nheqminer show following error -**
[10:57:22][0x00001270] stratum | Starting miner
[10:57:22][0x00001270] stratum | Connecting to stratum server 13.59.122.197:3333
[10:57:23][0x00001270] stratum | Connected!
[10:57:23][0x00001270] stratum | read_until: An existing connection was forcibly closed by the remote host
[10:57:23][0x00001270] stratum | Reconnecting in 3 seconds...

[btg.txt](https://github.com/z-classic/z-nomp/files/1718761/btg.txt)
[config.txt](https://github.com/z-classic/z-nomp/files/1718762/config.txt)
[pool.txt](https://github.com/z-classic/z-nomp/files/1718763/pool.txt)

**Comment by j4ys0n** [comment]
did you ever figure this out?

**Comment by nicebbs** [comment]
Have you solved the problem yet?
