### ISSUE TITLE
Getting Error TypeError: Cannot read property 'miner' of null

### ISSUE THREAD

**Issue by SanjaySaluth** [z-classic/z-nomp#291]
I am trying to run minexcoin in the pool.
Getting errror on npm start
Node Version Tried :
v7.1.0
v7.8.0
v9.5.0
OS : Ubuntu 16.04

TypeError: Cannot read property 'miner' of null
at /var/www/html/z-nomp/node_modules/stratum-pool/lib/pool.js:586:56
at itemFinished (/var/www/html/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
at /var/www/html/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
at parseJson (/var/www/html/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
at IncomingMessage. (/var/www/html/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
2018-02-15 13:53:03 [Master] [PoolSpawner] Fork 2 died, spawning replacement worker...

Any Idea, please?

**Comment by RepoBike** [comment]
I get the same errors

**Comment by TheComputerGenie** [comment]
Perhaps include the actual log and not just the excerpt that **you** _think_ is relevant...

**Comment by j4ys0n** [comment]
@SanjaySaluth did you solve this? i'm running into the same issue.
