### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by botio** [z-classic/z-nomp#298]
/home/botio/dnomp/node_modules/dot/doT.js:56
                return ((typeof block === "string") ? block : block.toString())
                                                                    ^

TypeError: Cannot read property 'toString' of undefined
    at resolveDefs (/home/botio/dnomp/node_modules/dot/doT.js:56:55)
    at Object.doT.template (/home/botio/dnomp/node_modules/dot/doT.js:94:33)
    at ReadFileContext.callback (/home/botio/dnomp/libs/website.js:84:33)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:441:13)
2018-03-04 13:02:30 [Master]    [Website] Website process died, spawning replacement...

Does anyone know how to fix it ? thank you so much.

**Comment by theicosuperman** [comment]
Are configs ok? Do this happens on startup?
