### ISSUE TITLE
Error with init.js

### ISSUE THREAD

**Issue by applitechnologies** [z-classic/z-nomp#343]
22 error z-nomp@0.0.4 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
22 error Exit status 1
23 error Failed at the z-nomp@0.0.4 start script 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the z-nomp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs z-nomp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls z-nomp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

--

> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2018-05-21 00:10:13 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
undefined:1
{"enabled":true,coin": "zcash_testnet.json","address": "tmL1czya8sNBfKjrT8JXncRJTrBDYSE3FG4","_comment_address": "atransparentaddresstosendcoinbaserewardstoandtotransfertozAddress.","zAddress": "ztqRQf9gupWD51VqN8MCw4f3G89bYW27hhiSYX2rZJoW9Y15jnEBv1djaf3CTGZ5oWwTE2kaEG9kDodUvo22DEVDoBVcefN","_comment_zAddress": "aprivateaddressusedtosendcoinstotAddress.","tAddress": "tmKRDPf5enB94eTyiv9JsB4vWs4sJRGxqa7","_comment_tAddress": "transparentaddressusedtosendpayments,makethisadifferentaddress,otherwisepaymentswillnotsen$"walletInterval":2.5,"rewardRecipients":{},"paymentProcessing":{"minConf":10,"enabled":true,"paymentMode":"prop","_comment_paymentMode":"prop, pplnt","paymentInterval":20,"minimumPayment":0.1,"maxBlocksPerPayment":3,"daemon":{"host":"127.0.0.1","port":2500,"user":"zcashrpc","password":"replaceme"}},"tlsOptions":{"enabled":false,"serverKey":"","serverCert":"","ca":""},"ports":{"3032":{"diff":0.05,"tls":false,"varDiff":{"minDiff":0.04,"maxDiff":16,"targetTime":15,"retargetTime":60,"varia

SyntaxError: Unexpected token c
    at Object.parse (native)
    at /home/appli/z-nomp/init.js:100:32
    at Array.forEach (native)
    at buildPoolConfigs (/home/appli/z-nomp/init.js:98:31)
    at init (/home/appli/z-nomp/init.js:505:19)
    at Object.<anonymous> (/home/appli/z-nomp/init.js:517:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

**Comment by knilecrack** [comment]
what version of node/npm do you have?

**Comment by EvilRedHorse** [comment]
- you need opening/closing double quotes around the _element_ named "coin", I see only a closing double quote.

{"enabled":"true",**coin"**: "zcash_testnet.json","address"     ...before

{"enabled":true,**"coin"**: "zcash_testnet.json","address"    ...after

- You likely are not going to mine to the zcash_testnet and should change the _value_ in the _element_ "enabled" to "false"

{**"enabled":false**,**"coin"**: "zcash_testnet.json","address"    ...after disabling zcash_testnet

- JSON data is sensitive, you can run your JSON through an online validator or chrome has a JSON-validator-plugin, data security becomes an issue at this point, you could obfuscate your wallet and pool addresses prior to running the validator.

- Don't randomly double quote numbers or true/false, they are likely being interpreted as an integers and booleans, not as a string.

**Comment by ssowellsvt** [comment]
You need to download and install the following: (It's actually in the ReadMe)

Node.js v7+ https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager
Redis key-value store v2.6+ http://redis.io/topics/quickstart

Then get the rest of the depends, git pull the repo and npm update/install

**Comment by EvilRedHorse** [comment]
They seem to have node and redis. I do not see that as the problem from experience.
