### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by jienis** [z-classic/z-nomp#360]
/home/pool/z-nomp/node_modules/typeforce/index.js:159
          throw tfSubError(e, i)
          ^
Error: Expected property "1" of type Satoshi, got Number 247500000000042530
    at tfSubError (/home/pool/z-nomp/node_modules/typeforce/errors.js:93:9)
    at /home/pool/z-nomp/node_modules/typeforce/index.js:159:17
    at Array.every (<anonymous>)
    at _tuple (/home/pool/z-nomp/node_modules/typeforce/index.js:155:20)
    at typeforce (/home/pool/z-nomp/node_modules/typeforce/index.js:196:9)
    at Transaction.addOutput (/home/pool/z-nomp/node_modules/bitcoinjs-lib-zcash/src/transaction.js:287:3)
    at Object.exports.createGeneration (/home/pool/z-nomp/node_modules/stratum-pool/lib/transactions.js:118:12)
    at new BlockTemplate (/home/pool/z-nomp/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/home/pool/z-nomp/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /home/pool/z-nomp/node_modules/stratum-pool/lib/pool.js:588:66
2018-07-04 13:27:25 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...

why????????????????????  help ,i love you

**Comment by TheComputerGenie** [comment]
What coin? What config? People need context in order to assist.

**Comment by jienis** [comment]
what your telegram , i add you

**Comment by TheComputerGenie** [comment]
I live in a modern country, we haven't sent telegrams in over 100 years.

**Comment by fsql** [comment]
@TheComputerGenie  Cloud you give me your QQ number or wechat ? I met the same problem.
