### ISSUE TITLE
stratum rejecting shares from z9 mini asic

### ISSUE THREAD

**Issue by asherwiswell** [z-classic/z-nomp#373]
I get the following errors when I try to connect my z9 mini to my pool:

2018-09-07 03:50:44 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
2018-09-07 03:50:44 [Pool]      [komodo] (Thread 2) Authorized RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9:x [::ffff:67.168.xxx.xx]
2018-09-07 03:50:45 [Pool]      [komodo] (Thread 2) Unknown stratum method from RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9.noname [::ffff:67.168.xxx.xx]: mining.multi_version
2018-09-07 03:50:46 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2018-09-07 03:50:46 [Pool]      [komodo] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2018-09-07 03:50:46 [Pool]      [komodo] (Thread 1) Stratum Pool Server Started for komodo [KMD] {equihash}
                                                Network Connected:      Mainnet
                                                Detected Reward Type:   POW
                                                Current Block Height:   998771
                                                Current Block Diff:     89641.427302753
                                                Current Connect Peers:  19
                                                Network Difficulty:     43609157.76693813
                                                Network Hash Rate:      11.16 MH
                                                Stratum Port(s):        3055
                                                Pool Fee Percent:       0.1%
                                                Block polling every:    600 ms
2018-09-07 03:50:46 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start
Invalid solution: invalid collision length between StepRows
X[i]   = 01e9d3077e8e0c2fe20e67e40d3d3e044836041dca06d04806df2c04422f
X[i+1] = 0031aa07d5f00b64ac0bf837072f9a058430059ad202527d0de16308101c
*** stack smashing detected ***: /home/asher/.nvm/versions/node/v8.9.4/bin/node terminated
2018-09-07 03:50:49 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...
2018-09-07 03:50:50 [Pool]      [komodo] (Thread 3) Authorized RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9:x [::ffff:67.168.xxx.xx]
2018-09-07 03:50:50 [Pool]      [komodo] (Thread 3) Unknown stratum method from RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9.noname [::ffff:67.168.xxx.xx]: mining.multi_version
Invalid solution: invalid collision length between StepRows
X[i]   = 0bdf3403c8e80b15d80c0bd20d05d70faf0e04c1910b17d50a9add033cf6
X[i+1] = 033133078e2d0a808a0e5199093e95050eb903172f05bd1905bc720b0af0
*** stack smashing detected ***: /home/asher/.nvm/versions/node/v8.9.4/bin/node terminated
2018-09-07 03:50:50 [Master]    [PoolSpawner] Fork 2 died, spawning replacement worker...
2018-09-07 03:50:51 [Pool]      [komodo] (Thread 4) Authorized RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9:x [::ffff:67.168.xxx.xx]
2018-09-07 03:50:52 [Pool]      [komodo] (Thread 4) Unknown stratum method from RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9.noname [::ffff:67.168.xxx.xx]: mining.multi_version
2018-09-07 03:50:52 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2018-09-07 03:50:52 [Pool]      [komodo] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2018-09-07 03:50:52 [Pool]      [komodo] (Thread 2) Stratum Pool Server Started for komodo [KMD] {equihash}
2018-09-07 03:50:52 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start
Invalid solution: invalid collision length between StepRows
X[i]   = 0921310829d208495d0ee3310275d20620bb02da700ef6fe025b780beaa9
X[i+1] = 00a03c0ec66302c2300bee8b07032d0627f701028a0f03b80ae9b60b427e
*** stack smashing detected ***: /home/asher/.nvm/versions/node/v8.9.4/bin/node terminated
2018-09-07 03:50:52 [Master]    [PoolSpawner] Fork 3 died, spawning replacement worker...
2018-09-07 03:50:53 [Switching] [Setup] (Thread 3) Loading last proxy state from redis
2018-09-07 03:50:53 [Pool]      [komodo] (Thread 3) Share processing setup with redis (127.0.0.1:6379)
2018-09-07 03:50:53 [Pool]      [komodo] (Thread 1) Authorized RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9:x [::ffff:67.168.xxx.xx]
2018-09-07 03:50:53 [Pool]      [komodo] (Thread 3) Stratum Pool Server Started for komodo [KMD] {equihash}
2018-09-07 03:50:53 [Switching] [Setup] (equihash) Setting proxy difficulties after pool start
2018-09-07 03:50:53 [Pool]      [komodo] (Thread 1) Share rejected: {"job":"ccce","ip":"::ffff:67.168.xxx.xx","worker":"RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9.noname","difficulty":1,"error":"job not found"}
2018-09-07 03:50:53 [Pool]      [komodo] (Thread 1) Share rejected: {"job":"ccce","ip":"::ffff:67.168.xxx.xx","worker":"RXJGBnSyULKKPhFGHjHaHQpXCzXUtibjb9.noname","difficulty":1,"error":"job not found"}

I was able to connect and accept shares using a gpu miner with claymore. And I have tested out the z9 mini on another pool and it works there.

**Comment by Jerry170617** [comment]
@coinpuddleclub Is the problem solved? I had the same problem.

**Comment by asherwiswell** [comment]
> @coinpuddleclub Is the problem solved? I had the same problem.

I couldn't find any info on making it work, so I am switching to s-nomp.  Cloned that repository and tried it out and it worked.  So now I'm in the process of re-doing all the custom changes I made.

**Comment by Jerry170617** [comment]
@coinpuddleclub /home/pool/snomp/node_modules/base-x/index.js:52
    if (typeof string !== 'string') throw new TypeError('Expected String')
                                    ^

TypeError: Expected String
    at decodeUnsafe (/home/pool/snomp/node_modules/base-x/index.js:52:43)
    at Object.decode (/home/pool/snomp/node_modules/base-x/index.js:81:18)
    at Object.decode (/home/pool/snomp/node_modules/bs58check/base.js:39:25)
    at Object.fromBase58Check (/home/pool/snomp/node_modules/bitcoinjs-lib-zcash/src/address.js:11:27)
    at Object.exports.createGeneration (/home/pool/snomp/node_modules/stratum-pool/lib/transactions.js:133:56)
    at new BlockTemplate (/home/pool/snomp/node_modules/stratum-pool/lib/blockTemplate.js:59:35)
    at JobManager.processTemplate (/home/pool/snomp/node_modules/stratum-pool/lib/jobManager.js:155:32)
    at /home/pool/snomp/node_modules/stratum-pool/lib/pool.js:601:66
    at itemFinished (/home/pool/snomp/node_modules/stratum-pool/lib/daemon.js:166:36)
    at /home/pool/snomp/node_modules/stratum-pool/lib/daemon.js:180:17

**Comment by Jerry170617** [comment]
Does the s-nomp error help?

**Comment by asherwiswell** [comment]
I'm not getting those errors at all.  Those look like syntax errors in those particular files. But I'm not a javascript expert by any means.

**Comment by Jerry170617** [comment]
Invalid solution: invalid collision length between StepRows
X[i]   = 091c9e0f46490f9a8f04e7ec001f590496cb08c4b90a70cb0f4f3804749c
X[i+1] = 0447cc09170b0457a100a879067f07075ca6073e5f06caad098bd802a303

**Comment by Jerry170617** [comment]
I run s-nomp Branch: feat / zero-founders-reward.
The above problems have arisen.
I wonder if you have a similar problem.

**Comment by asherwiswell** [comment]
> I run s-nomp Branch: feat / zero-founders-reward.
> The above problems have arisen.
> I wonder if you have a similar problem.

I would probably ask this question in the S-Nomp Issues section, not here.

**Comment by TheComputerGenie** [comment]
Not that there was ever much support for Komodo in z-nomp to begin with, but all z-nomp support became non-existent with Overwinter changes. Look to the Komodo community for one of the forks that are supported.
