### ISSUE TITLE
npm update error ！！npm ERR! equihashverify@0.0.3 install: `env V=1 node-gyp rebuild`

### ISSUE THREAD

**Issue by hysystem** [z-classic/z-nomp#374]
In file included from ../arith_uint256.cpp:10:0:
../crypto/common.h:11:20: fatal error: sodium.h: No such file or directory
 #include "sodium.h"
                    ^
compilation terminated.
make: *** [Release/obj.target/equihashverify/arith_uint256.o] Error 1
make: Leaving directory `/data/z-nomp/node_modules/equihashverify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-693.2.2.el7.x86_64
gyp ERR! command "/root/.nvm/versions/node/v8.11.1/bin/node" "/root/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/z-nomp/node_modules/equihashverify
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! equihashverify@0.0.3 install: `env V=1 node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the equihashverify@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-10T02_55_20_791Z-debug.log

**Comment by Superpassteque** [comment]
same error on ubuntu 18.04

**Comment by igorvoltaic** [comment]
Install libsodium
Might be different name in different distros
