### ISSUE TITLE
Pools fails to start with TLS disabled

### ISSUE THREAD

**Issue by EliteMobb79** [z-classic/z-nomp#88]
I have TLS disabled in the pool config and keep getting a tls error when I try to start the pool. Here is the error I am getting

`_tls_wrap.js:888
  if (typeof options.requestCert === 'boolean') {
                    ^

TypeError: Cannot read property 'requestCert' of undefined
    at Server.setOptions (_tls_wrap.js:888:21)
    at new Server (_tls_wrap.js:766:8)
    at Object.exports.createServer (_tls_wrap.js:861:10)
    at /home/elitemobb/z-nomp/node_modules/stratum-pool/lib/stratum.js:467:21
    at Array.forEach (native)
    at init (/home/elitemobb/z-nomp/node_modules/stratum-pool/lib/stratum.js:457:36)
    at new StratumServer (/home/elitemobb/z-nomp/node_modules/stratum-pool/lib/stratum.js:476:7)
    at StartStratumServer (/home/elitemobb/z-nomp/node_modules/stratum-pool/lib/pool.js:442:31)
    at /home/elitemobb/z-nomp/node_modules/stratum-pool/lib/pool.js:55:25
    at /home/elitemobb/z-nomp/node_modules/stratum-pool/lib/pool.js:91:13`

Here is the tls and port settings in the config

   ` "tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

    "ports": {
        "7100": {
            "diff": 0.05,
            "tls": false,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },`

**Comment by aayanl** [comment]
should be fixed now

**Comment by EliteMobb79** [comment]
Pool starts now. Issue resolved. Thanks
