### ISSUE TITLE
Zec Payment not working

### ISSUE THREAD

**Issue by sonicdx10** [z-classic/z-nomp#93]
Other equihash crypto are working ok

server      mexpool.ddns.net

/home/dimi/z-nomp/libs/paymentProcessor.js:172
                for (var i = 0, len = result[0].response.length; i < len; i++) {
                                                        ^

TypeError: Cannot read property 'length' of null
    at /home/dimi/z-nomp/libs/paymentProcessor.js:172:57
    at /home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:175:17
    at /home/dimi/z-nomp/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/home/dimi/z-nomp/node_modules/async/dist/async.js:935:13)
    at /home/dimi/z-nomp/node_modules/async/dist/async.js:843:16
    at itemFinished (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:157:17)
    at /home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/dimi/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
    at emitNone (events.js:91:20)
2017-03-07 08:05:48 [Master]    [Payment Processor] Payment processor died, spawning replacement...

**Comment by aayanl** [comment]
usually this error indicates the payment processor can't connect to the main zcash node

**Comment by 6otah** [comment]
@aayanl 
I have the same error. My zcash node runs on another server. I added host, port, user, pass in paymentProcessing - daemon and in daemons sections in pool config; added ip of znomp pool in coin daemon config file.
When I delete rpcallowip line in zcash config I get this output:

```
2017-03-08 13:20:26 [Payments]  [zcash] Could not parse rpc data from daemon instance  0
Request Data: {"method":"validateaddress","params":["t1KE......"],"id":1488972026193}
Reponse Data: Forbidden
```

Does this mean znomp actually can connect to zcash node?

**Comment by sonicdx10** [comment]
yup, just zec is not working with paymentsproc, did a few movements without success :(

**Comment by aayanl** [comment]
you need -rpcallowip if want to connect to a remote node

**Comment by sonicdx10** [comment]
Is not on remote server no need special port or ipallow, is on local  ^.-?

**Comment by 6otah** [comment]
@aayanl 
I have -rpcallowip line, payment processor still dies and respawns.

**Comment by sonicdx10** [comment]
Tried to change VPS, compile, blah blah several times, and the only equihash coin that doesn't work with payment processor is ZEC... got server up and running on alvblock.com (komodo, zclassic, zdash)

**Comment by aayanl** [comment]
can you copy and paste your zcash pool conifg?

**Comment by sonicdx10** [comment]
{
    "enabled": true,
    "coin": "zcash.json",

    "address": "tadd1",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zaddr",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "tadd2",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "walletInterval": 10,

    "rewardRecipients": {
        "tadd2": 0.2, "tadd4": 0.8},

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 2000,
        "minimumPayment": 0.01,
        "daemon": {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "user",
            "password": "u--------asd-fa-dsf--ads-f-a-sdf--as-fd-ad-="
        }
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

    "ports": {
        "3032": {
            "diff": 0.05,
            "tls": false,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "user",
            "password": "u--------asd-fa-dsf--ads-f-a-sdf--as-fd-ad-="
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "user",
        "password": "user",
        "database": "mpos",
        "checkPassword": false,
        "autoCreateWorker": true
    }

}

**Comment by sonicdx10** [comment]
Fixed with last git but now komodo pool doesn't start

**Comment by aayanl** [comment]
Glad to see zcash payments work, ill see whats up with Komodo

**Comment by sonicdx10** [comment]
Komodo running with (succes on 4 pools) what does that affect? to the other 3 coins?

`// generate the fees and coinbase tx
    var blockReward = (this.rpcData.miner + this.rpcData.founders) * 100000000;
`
`    // generate the fees and coinbase tx
    var blockReward = (this.rpcData.miner) * 100000000;`

**Comment by aayanl** [comment]
The first one is for zcash to include the founder's reward, the second one pays everything to the miner for zclassic

**Comment by sonicdx10** [comment]
ok then the 4 pools (zec, zdash, zcl, kmd) are working with Second Option

**Comment by aayanl** [comment]
you need the first one for zcash otherwise blocks will get rejected

**Comment by aayanl** [comment]
for not including the founders tax

**Comment by sonicdx10** [comment]
thx 4 your help

**Comment by sonicdx10** [comment]
so at it is can't be possible to run komodo and zec on same stratum?

**Comment by aayanl** [comment]
no

**Comment by glasswool** [comment]
Hi. Need help to resolve following errors:
2017-07-16 11:05:55 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-07-16 11:05:55 [Master]	[CLI] CLI listening on port 17117
2017-07-16 11:05:55 [PPLNT]	[zcash] TimeShare processing setup with redis (127.0.0.1:6379)
2017-07-16 11:05:56 [Website]	[Server] Website started on 0.0.0.0:8080
2017-07-16 11:05:56 [Website]	[zcash] Could not dumpprivkey for zcash {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:05:56 [Payments]	[zcash] paymentInterval of 180 seconds recommended to reduce the RPC work queue.
2017-07-16 11:05:56 [Payments]	[zcash] zcash requireShielding: true
2017-07-16 11:05:56 [Payments]	[zcash] zcash minConf: 10
2017-07-16 11:05:56 [Payments]	[zcash] zcash payments txfee reserve: 0.0004
2017-07-16 11:05:56 [Payments]	[zcash] zcash maxBlocksPerPayment: 3
2017-07-16 11:05:56 [Payments]	[zcash] zcash PPLNT: false, time period: 0.51
2017-07-16 11:05:56 [Payments]	[zcash] Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:05:56 [Payments]	[zcash] Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:05:56 [Payments]	[zcash] Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:05:56 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2017-07-16 11:05:56 [Pool]	[zcash] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2017-07-16 11:05:56 [Pool]	[zcash] (Thread 1) Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 192.168.13.120:8232"}
2017-07-16 11:05:56 [Master]	[PoolSpawner] Spawned 1 pool(s) on 4 thread(s)
2017-07-16 11:05:57 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
2017-07-16 11:05:57 [Pool]	[zcash] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2017-07-16 11:05:57 [Pool]	[zcash] (Thread 2) Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 192.168.13.120:8232"}
2017-07-16 11:05:57 [Switching]	[Setup] (Thread 3) Loading last proxy state from redis
2017-07-16 11:05:57 [Pool]	[zcash] (Thread 3) Share processing setup with redis (127.0.0.1:6379)
2017-07-16 11:05:57 [Pool]	[zcash] (Thread 3) Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 192.168.13.120:8232"}
2017-07-16 11:05:57 [Switching]	[Setup] (Thread 4) Loading last proxy state from redis
2017-07-16 11:05:57 [Pool]	[zcash] (Thread 4) Share processing setup with redis (127.0.0.1:6379)
2017-07-16 11:05:57 [Pool]	[zcash] (Thread 4) Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 192.168.13.120:8232"}
2017-07-16 11:06:53 [Payments]	[zcash] Error with RPC call z_getoperationstatus {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:06:54 [Payments]	[zcash] Error with RPC call getmininginfo {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}

**Comment by glasswool** [comment]
Hi, Need help with the following errors...:
2017-07-16 11:09:35 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-07-16 11:09:35 [Master]	[CLI] CLI listening on port 17117
2017-07-16 11:09:35 [PPLNT]	[zcash] TimeShare processing setup with redis (127.0.0.1:6379)
2017-07-16 11:09:35 [Payments]	[zcash] paymentInterval of 180 seconds recommended to reduce the RPC work queue.
2017-07-16 11:09:35 [Payments]	[zcash] zcash requireShielding: true
2017-07-16 11:09:35 [Payments]	[zcash] zcash minConf: 10
2017-07-16 11:09:35 [Payments]	[zcash] zcash payments txfee reserve: 0.0004
2017-07-16 11:09:35 [Payments]	[zcash] zcash maxBlocksPerPayment: 3
2017-07-16 11:09:35 [Payments]	[zcash] zcash PPLNT: false, time period: 0.51
2017-07-16 11:09:35 [Payments]	[zcash] Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:09:35 [Payments]	[zcash] Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:09:35 [Payments]	[zcash] Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:09:35 [Website]	[Server] Website started on 0.0.0.0:8080
2017-07-16 11:09:35 [Website]	[zcash] Could not dumpprivkey for zcash {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}
2017-07-16 11:09:36 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2017-07-16 11:09:36 [Pool]	[zcash] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2017-07-16 11:09:36 [Pool]	[zcash] (Thread 1) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getinfo","params":[],"id":1500183576131}
Reponse Data: 
2017-07-16 11:09:36 [Master]	[PoolSpawner] Spawned 1 pool(s) on 4 thread(s)
2017-07-16 11:09:36 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
2017-07-16 11:09:36 [Pool]	[zcash] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2017-07-16 11:09:36 [Pool]	[zcash] (Thread 2) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getinfo","params":[],"id":1500183576387}
Reponse Data: 
2017-07-16 11:09:36 [Switching]	[Setup] (Thread 3) Loading last proxy state from redis
2017-07-16 11:09:36 [Pool]	[zcash] (Thread 3) Share processing setup with redis (127.0.0.1:6379)
2017-07-16 11:09:36 [Pool]	[zcash] (Thread 3) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getinfo","params":[],"id":1500183576540}
Reponse Data: 
2017-07-16 11:09:36 [Switching]	[Setup] (Thread 4) Loading last proxy state from redis
2017-07-16 11:09:36 [Pool]	[zcash] (Thread 4) Share processing setup with redis (127.0.0.1:6379)
2017-07-16 11:09:36 [Pool]	[zcash] (Thread 4) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getinfo","params":[],"id":1500183576770}

**Comment by miningmining** [comment]
Hi,

I have some issues as well... Is there anyone who wants to setup a project for me?
Contact me at skype: patrickdegroot007
